---
version: '3.5'
services:
  dev_k6:
    image: setsoft/kicad_auto:dev_k6
    working_dir: /workdir
    environment:
      DISPLAY: host.docker.internal:0.0
      NO_AT_BRIDGE: 1
    volumes: [.:/workdir, .cache/kicad:/workdir/.cache]
    command: make
