#!/bin/bash
#IMAGE=setsoft/kicad_auto:10.3-5.1.5
IMAGE=setsoft/kicad_auto:dev
#IMAGE=setsoft/kicad_auto:latest
#IMAGE=setsoft/kicad_auto:10.4-5.1.6rc
export USER_ID=$(id -u)
export GROUP_ID=$(id -g)
# Using root on windows
USER_ID=0
group_ID=0
export WORKDIR=$(realpath "$(dirname $0)/..")
export SUBDIR=$(basename $0)
export WORKDIR=$(realpath "$(dirname $0)")
export SUBDIR=.
export DISPLAY=${DISPLAY:=0}
export HOMEDIR=$(realpath "$(dirname $0)/..")/kibotHome
if [ ${USER_ID} != 0 ] ; then
  export TGTHOMEDIR="/home/${USER}"
else
  export TGTHOMEDIR="/root"
fi

# Quote arguments
ARGS=""
for i in "$@" ; do
    ARGS=$ARGS" '"${i/\'/\\\'}"'"
done
#ARGS="$@"

# In case of windows batch
# for /f "delims=[] tokens=2" %%a in ('ping -4 -n 1 %ComputerName% ^| findstr [') do set NetworkIP=%%a
# echo Network IP: %NetworkIP
IP=$(ping -4 -n 1 ${COMPUTERNAME}|head -2|tail -1|perl -p -e 's/^.*?\[(.*?)\].*/$1/;')
DISPLAY=$IP:0.0

DISPLAY=host.docker.internal:0.0

mkdir -p $HOMEDIR
WORKDIR=$(cygpath -w "$WORKDIR")
HOMEDIR=$(cygpath -w "$HOMEDIR")
#
# passwd & shadow not propagated on windows, using root user
#  --user $USER_ID:$GROUP_ID \
#ETC=$(cygpath -w "/etc")
#ETC=/etc
#    --volume="${ETC}/passwd:/etc/passwd:ro" \
#    --volume="${ETC}/shadow:/etc/shadow:ro" \
#    --volume="${ETC}/group:/etc/group:ro" \
#
#echo $ARGS
LOCAL_KICAD_DIR=$(cygpath 'C:\Program Files\KiCad\share\kicad')
LOCAL_KICAD_LIBDIR=$(cygpath -d -w "$LOCAL_KICAD_DIR/library")
LOCAL_KICAD_MODULESDIR=$(cygpath -d -w "$LOCAL_KICAD_DIR/modules")
LOCAL_KICAD_LIB_SETTING="--volume=${LOCAL_KICAD_LIBDIR}:/usr/share/kicad/library:ro --volume=${LOCAL_KICAD_MODULESDIR}:/usr/share/kicad/modules:ro"

#LOCAL_KBOTREPO="--volume=$(cygpath -w /cygdrive/d/mdeweerd/KiCAD/kibot-repo/kibot):/usr/lib/python3.7/dist-packages/kibot:rw"

LOCAL_KIAUTOREPO="--volume=$(cygpath -w /cygdrive/d/mdeweerd/KiCAD/KiAuto/kiauto):/usr/lib/python3/dist-packages/kiauto:rw"
LOCAL_KIAUTOREPO="${LOCAL_KIAUTOREPO} --volume=$(cygpath -w /cygdrive/d/mdeweerd/KiCAD/KiAuto/src/pcbnew_do):/usr/bin/pcbnew_do:rw"
LOCAL_KIAUTOREPO="${LOCAL_KIAUTOREPO} --volume=$(cygpath -w /cygdrive/d/mdeweerd/KiCAD/KiAuto/src/eeschema_do):/usr/bin/eeschema_do:rw"

#LOCAL_KBOTREPO="--volume=$(cygpath -w /cygdrive/d/mdeweerd/KiCAD/KiAuto/kiauto/eeschema_do):/usr/lib/python3.7/dist-packages/kiaut:rw"
#LOCAL_KBOTREPO="--volume=$(cygpath -w /cygdrive/d/mdeweerd/KiCAD/kibot):${TGTHOMEDIR}/kibot:rw"
LOCAL_KBOTREPO="--volume=$(cygpath -w /cygdrive/d/mdeweerd/KiCAD/kibot/kibot):/usr/local/lib/python3.7/dist-packages/kibot:rw"
LOCAL_KBOTREPO=
LOCAL_KIAUTOREPO=
if [ "$ARGS" == "" ] ; then
  ARGS=bash
fi
docker run --rm -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY \
    ${LOCAL_KICAD_LIB_SETTING} \
    ${LOCAL_KBOTREPO} \
    ${LOCAL_KIAUTOREPO} \
    -v $WORKDIR:${TGTHOMEDIR}/workdir \
    --env NO_AT_BRIDGE=1 \
    --workdir="${TGTHOMEDIR}" \
    ${LOCAL_KICAD_LIB_SETTING} \
    --volume="${HOMEDIR}/.config/kicad:${TGTHOMEDIR}/.config/kicad:rw" \
    --volume="${HOMEDIR}/.cache/kicad:${TGTHOMEDIR}/.cache/kicad:rw" \
    $IMAGE /bin/bash -c "cd workdir/$SUBDIR ; $ARGS" \
| tee $1.log
